name       : perl-http-message
version    : 6.11
release    : 5
source     :
    - http://search.cpan.org/CPAN/authors/id/E/ET/ETHER/HTTP-Message-6.11.tar.gz : e7b368077ae6a188d99920411d8f52a8e5acfb39574d4f5c24f46fd22533d81b
license    : Artistic-1.0-Perl
summary    : Perl HTTP Message Module
component  : programming.perl
description: |
    Perl HTTP Message Module
patterns   :
    - /usr/share/man
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
