name       : perl-http-message
version    : 6.14
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Message-6.14.tar.gz : 71aab9f10eb4b8ec6e8e3a85fc5acb46ba04db1c93eb99613b184078c5cf2ac9
license    : Artistic-1.0-Perl
summary    : Perl HTTP Message Module
component  : programming.perl
description: |
    Perl HTTP Message Module
patterns   :
    - /usr/share/man
builddeps  :
    - perl-encode-locale
    - perl-http-date
    - perl-io-html
    - perl-lwp-mediatypes
    - perl-try-tiny
    - perl-uri
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
