name       : perl-http-message
version    : '6.37'
release    : 14
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTTP-Message-6.37.tar.gz : 0e59da0a85e248831327ebfba66796314cb69f1bfeeff7a9da44ad766d07d802
homepage   : https://github.com/libwww-perl/HTTP-Message
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : HTTP::Message - HTTP style message (base class)
description: |
    An HTTP::Message object contains some headers and a content body.
builddeps  :
    - perl-encode-locale
    - perl-http-date
    - perl-io-html
    - perl-lwp-mediatypes
    - perl-test-needs
    - perl-try-tiny
    - perl-uri
rundeps    :
    - perl-encode-locale
    - perl-http-date
    - perl-io-html
    - perl-lwp-mediatypes
    - perl-uri
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
