name       : perl-http-message
version    : '6.16'
release    : 8
source     :
    - https://github.com/libwww-perl/HTTP-Message/archive/v6.16.tar.gz : 946c94b7ad73b041a14e3d8d40ced33f9b858d934effb4b7ba3197a7342e4209
license    : Artistic-1.0-Perl
summary    : Perl HTTP Message Module
component  : programming.perl
description: |
    Perl HTTP Message Module
homepage   : https://github.com/libwww-perl/HTTP-Message
builddeps  :
    - perl-encode-locale
    - perl-http-date
    - perl-io-html
    - perl-lwp-mediatypes
    - perl-try-tiny
    - perl-uri
rundeps    :
    - perl-encode-locale
    - perl-http-date
    - perl-io-html
    - perl-lwp-mediatypes
    - perl-uri
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
