name       : perl-http-message
version    : '6.18'
release    : 11
source     :
    - https://github.com/libwww-perl/HTTP-Message/archive/v6.18.tar.gz : a270cecc84bf3b8420d1790b37755527bc2d8eb51ad54cb81681aaafb94e30e1
license    : Artistic-1.0-Perl
summary    : Perl HTTP Message Module
component  : programming.perl
description: |
    Perl HTTP Message Module
homepage   : https://github.com/libwww-perl/HTTP-Message
builddeps  :
    - perl-encode-locale
    - perl-http-date
    - perl-io-html
    - perl-lwp-mediatypes
    - perl-try-tiny
    - perl-uri
rundeps    :
    - perl-encode-locale
    - perl-http-date
    - perl-io-html
    - perl-lwp-mediatypes
    - perl-uri
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
